# Generated by Django 5.1.7 on 2025-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone",
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("HOME", "Home"), ("WORK", "Work"), ("OTHER", "Other")],
                default="HOME",
                max_length=10,
            ),
        ),
    ]
